version: '2.3'

services:
  notebooks:
    build: 
      context: ./docker/jupyter
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/nb
      - ./data:/data
  fastapi:
    build:
      context: ./docker/fastapi
    ports:
      - 8000:8000
    volumes:
      - ./api:/api